### ISSUE TITLE
feat(color): 为高版本渐变颜色增加 加粗 斜体 下划线 等特殊功能

### ISSUE THREAD

**Issue by RedCarl** [CarmJos/EasyPlugin#9]
### **功能简述**

兼容 &l &m &n &k &o &r

### **需求来源**

需要对渐变颜色进行加粗等特殊效果。

### **附加内容**

需要注意有的时候加粗可能不是开头，也可能是在中间，只加粗渐变字中的某个字。

**Comment by RedCarl** [comment]
如果可以建议整合MiniMessage让Component使用起来更加方便。velocity 无法使用颜色符号

**Comment by CarmJos** [comment]
> 

暂不考虑整合MiniMessages，微型项目不应捆绑大型类库，有相关需要的可以自行依赖。

**Comment by CarmJos** [comment]
检查了一下，好像已经支持给中间的某个字添加特殊形式了。回忆起来先前不做格式传递正是如此。

**Comment by CarmJos** [comment]
见 https://github.com/CarmJos/EasyPlugin/blob/01250a65d13660ca7f08bf1447abb560f5d3bb10/base/color/src/main/java/cc/carm/lib/easyplugin/utils/ColorParser.java#L131

**Comment by CarmJos** [comment]
该功能已在 https://github.com/CarmJos/EasyPlugin/releases/tag/1.5.8 中支持，请帮助测试使用。
